# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: mtblaser2002@gmail.com
author_name: ZeroToH3ro
contract_name: supply_chain
deployment_language: python
preset_name: production
project_name: SupplyChain-contracts

